// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ipuhfhlkukxkbclfsiym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwdWhmaGxrdWt4a2JjbGZzaXltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MjIyMDEsImV4cCI6MjA2MDQ5ODIwMX0.xoX0auQ31jWaZuOWpEwYC2-xzvT4j6leEzBNZ45Zb3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);